version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./public:/var/www/html/
    ports:
      - 8000:80
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - '9906:3306'
